### PR TITLE
MFA fix. Issue# 37

### PR DESCRIPTION
**Pull request by an-sush**
Fix for issue# [37](https://github.com/SonarQubeCommunity/sonar-auth-aad/issues/37)

### CODE REVIEW

**Comment by hkamel** [comment]
Thank you @an-sush  for the pull request

**Comment by an-sush** [comment]
Thanks @hkamel. Do you plan to create a release for this fix and potentially some other commits which have been done since last release in 2016

**Comment by hkamel** [comment]
@an-sush indeed, I'm working on a release that combines couple of enhancements and bug fixing.

**Comment by tyrone-grech** [comment]
Any updates on releasing this fix, please?

We ran into the same issue when we enabled MFA at our company.

**Pull request merged**
